services:

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coursemanager-network
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: coursemanager-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/CourseManager
    depends_on:
      - postgres
    networks:
      - coursemanager-network
    
  frontend:
    build:
      context: ./Frontend/course-manager
      dockerfile: Dockerfile
    container_name: coursemanager-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    networks:
      - coursemanager-network

networks:
    coursemanager-network:
      driver: bridge

volumes:
    postgres-data: